<?php
			$optionsArray = array( 'totals' => array( 'idusrglobal' => array( 'totalsType' => '' ),
'id_fk' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'usr_nombresfull' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_inicial' => array( 'totalsType' => '' ),
'usr_sessini' => array( 'totalsType' => '' ),
'usr_image' => array( 'totalsType' => '' ),
'usr_status_nomina' => array( 'totalsType' => '' ),
'usr_status' => array( 'totalsType' => '' ),
'usr_rdnkey' => array( 'totalsType' => '' ),
'usr_type_vinc' => array( 'totalsType' => '' ),
'usr_type_vinculacion' => array( 'totalsType' => '' ),
'usr_status_sol' => array( 'totalsType' => '' ),
'usr_dependencia' => array( 'totalsType' => '' ),
'user_dep' => array( 'totalsType' => '' ),
'usr_entidad' => array( 'totalsType' => '' ),
'usr_not' => array( 'totalsType' => '' ),
'usr_not_msj' => array( 'totalsType' => '' ),
'usr_jefe' => array( 'totalsType' => '' ),
'usr_minequipo_lider' => array( 'totalsType' => '' ),
'usr_minequipo_grupo' => array( 'totalsType' => '' ),
'global_rol_me' => array( 'totalsType' => '' ),
'global_rol_gh' => array( 'totalsType' => '' ),
'global_rol_almacen' => array( 'totalsType' => '' ),
'global_rol_ci' => array( 'totalsType' => '' ),
'global_rol_contratos' => array( 'totalsType' => '' ),
'global_rol_hojar' => array( 'totalsType' => '' ),
'global_rol_inmuebles' => array( 'totalsType' => '' ),
'global_rol_siis' => array( 'totalsType' => '' ),
'global_rol_cpanel' => array( 'totalsType' => '' ),
'global_rol_dashboard' => array( 'totalsType' => '' ),
'global_rol_zf' => array( 'totalsType' => '' ),
'global_rol_sipi' => array( 'totalsType' => '' ),
'global_rol_cej' => array( 'totalsType' => '' ),
'global_rol_jc3' => array( 'totalsType' => '' ),
'global_rol_th' => array( 'totalsType' => '' ),
'global_rol_sid' => array( 'totalsType' => '' ),
'global_rol' => array( 'totalsType' => '' ),
'global_rol_cont' => array( 'totalsType' => '' ),
'globla_rol_ct' => array( 'totalsType' => '' ),
'global_rol_procjur' => array( 'totalsType' => '' ),
'global_rol_comacc' => array( 'totalsType' => '' ),
'global_rol_gestion' => array( 'totalsType' => '' ),
'global_rol_ciudadano' => array( 'totalsType' => '' ),
'global_rol_ciudadano_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_time' => array( 'totalsType' => '' ),
'sys_ntries_usr' => array( 'totalsType' => '' ),
'sys_registrationdate_usr' => array( 'totalsType' => '' ),
'sys_expiration_usr' => array( 'totalsType' => '' ),
'sys_disabledate_usr' => array( 'totalsType' => '' ),
'sys_upd_fecha' => array( 'totalsType' => '' ),
'sys_upd_user' => array( 'totalsType' => '' ),
'sys_upd_time' => array( 'totalsType' => '' ),
'sys_update_info' => array( 'totalsType' => '' ),
'sys_update_family_info' => array( 'totalsType' => '' ),
'usr_update_almacen' => array( 'totalsType' => '' ),
'sys_anio' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'ext_security_id' => array( 'totalsType' => '' ),
'covid_sn' => array( 'totalsType' => '' ),
'covid_fecha' => array( 'totalsType' => '' ),
'vacuna_sn' => array( 'totalsType' => '' ),
'vacuna_nombre' => array( 'totalsType' => '' ),
'vacuna_a_fecha' => array( 'totalsType' => '' ),
'vacuna_b_fechaprog' => array( 'totalsType' => '' ),
'vacuna_b_fecha' => array( 'totalsType' => '' ),
'vacuna_c_fecha' => array( 'totalsType' => '' ),
'vacuna_consentimiento_sn' => array( 'totalsType' => '' ),
'vacuna_obs' => array( 'totalsType' => '' ),
'vacuna_dosis' => array( 'totalsType' => '' ),
'vacuna_interes' => array( 'totalsType' => '' ),
'vacuna_etapa' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_dep_sup' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'usr_regpago' => array( 'totalsType' => '' ),
'usr_extension' => array( 'totalsType' => '' ),
'usr_piso' => array( 'totalsType' => '' ),
'usr_datebirth' => array( 'totalsType' => '' ),
'ctrl_pedidoalmacen' => array( 'totalsType' => '' ),
'ctrl_contacto' => array( 'totalsType' => '' ),
'usr_emergencia' => array( 'totalsType' => '' ),
'upd_date' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'habilita_almacen' => array( 'totalsType' => '' ),
'estado_vinculacion_mincit' => array( 'totalsType' => '' ),
'usr_firma' => array( 'totalsType' => '' ),
'usr_firma_b' => array( 'totalsType' => '' ),
'usr_hojaruta' => array( 'totalsType' => '' ),
'reset_token' => array( 'totalsType' => '' ),
'reset_date' => array( 'totalsType' => '' ),
'usr_edl' => array( 'totalsType' => '' ),
'userpic' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'phone1' => array( 'totalsType' => '' ),
'usr_directivo' => array( 'totalsType' => '' ),
'vacuna_autoriza' => array( 'totalsType' => '' ),
'vacuna_autoriza_email' => array( 'totalsType' => '' ),
'two_factor' => array( 'totalsType' => '' ),
'totp' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'idusrglobal',
'id_fk',
'Username',
'Password',
'usr_email',
'usr_name',
'usr_lname',
'usr_nombresfull',
'usr_personalid',
'usr_inicial',
'usr_sessini',
'usr_image',
'usr_status_nomina',
'usr_status',
'usr_rdnkey',
'usr_type_vinc',
'usr_type_vinculacion',
'usr_status_sol',
'usr_dependencia',
'user_dep',
'usr_entidad',
'usr_not',
'usr_not_msj',
'usr_jefe',
'usr_minequipo_lider',
'usr_minequipo_grupo',
'global_rol_me',
'global_rol_gh',
'global_rol_almacen',
'global_rol_ci',
'global_rol_contratos',
'global_rol_hojar',
'global_rol_inmuebles',
'global_rol_siis',
'global_rol_cpanel',
'global_rol_dashboard',
'global_rol_zf',
'global_rol_sipi',
'global_rol_cej',
'global_rol_jc3',
'global_rol_th',
'global_rol_sid',
'global_rol',
'global_rol_cont',
'globla_rol_ct',
'global_rol_procjur',
'global_rol_comacc',
'global_rol_gestion',
'global_rol_ciudadano',
'global_rol_ciudadano_dep',
'sys_user',
'sys_date',
'sys_time',
'sys_ntries_usr',
'sys_registrationdate_usr',
'sys_expiration_usr',
'sys_disabledate_usr',
'sys_upd_fecha',
'sys_upd_user',
'sys_upd_time',
'sys_update_info',
'sys_update_family_info',
'usr_update_almacen',
'sys_anio',
'ctrl',
'ext_security_id',
'covid_sn',
'covid_fecha',
'vacuna_sn',
'vacuna_nombre',
'vacuna_a_fecha',
'vacuna_b_fechaprog',
'vacuna_b_fecha',
'vacuna_c_fecha',
'vacuna_consentimiento_sn',
'vacuna_obs',
'vacuna_dosis',
'vacuna_interes',
'vacuna_etapa',
'usr_dep',
'usr_dep_sup',
'usr_cargo',
'usr_regpago',
'usr_extension',
'usr_piso',
'usr_datebirth',
'ctrl_pedidoalmacen',
'ctrl_contacto',
'usr_emergencia',
'upd_date',
'active',
'groupid',
'habilita_almacen',
'estado_vinculacion_mincit',
'usr_firma',
'usr_firma_b',
'usr_hojaruta',
'reset_token',
'reset_date',
'usr_edl',
'phone',
'phone1',
'usr_directivo',
'vacuna_autoriza',
'vacuna_autoriza_email',
'two_factor',
'totp' ),
'exportFields' => array( 'idusrglobal',
'id_fk',
'Username',
'Password',
'usr_email',
'usr_name',
'usr_lname',
'usr_nombresfull',
'usr_personalid',
'usr_inicial',
'usr_sessini',
'usr_image',
'usr_status_nomina',
'usr_status',
'usr_rdnkey',
'usr_type_vinc',
'usr_type_vinculacion',
'usr_status_sol',
'usr_dependencia',
'user_dep',
'usr_entidad',
'usr_not',
'usr_not_msj',
'usr_jefe',
'usr_minequipo_lider',
'usr_minequipo_grupo',
'global_rol_me',
'global_rol_gh',
'global_rol_almacen',
'global_rol_ci',
'global_rol_contratos',
'global_rol_hojar',
'global_rol_inmuebles',
'global_rol_siis',
'global_rol_cpanel',
'global_rol_dashboard',
'global_rol_zf',
'global_rol_sipi',
'global_rol_cej',
'global_rol_jc3',
'global_rol_th',
'global_rol_sid',
'global_rol',
'global_rol_cont',
'globla_rol_ct',
'global_rol_procjur',
'global_rol_comacc',
'global_rol_gestion',
'global_rol_ciudadano',
'global_rol_ciudadano_dep',
'sys_user',
'sys_date',
'sys_time',
'sys_ntries_usr',
'sys_registrationdate_usr',
'sys_expiration_usr',
'sys_disabledate_usr',
'sys_upd_fecha',
'sys_upd_user',
'sys_upd_time',
'sys_update_info',
'sys_update_family_info',
'usr_update_almacen',
'sys_anio',
'ctrl',
'ext_security_id',
'covid_sn',
'covid_fecha',
'vacuna_sn',
'vacuna_nombre',
'vacuna_a_fecha',
'vacuna_b_fechaprog',
'vacuna_b_fecha',
'vacuna_c_fecha',
'vacuna_consentimiento_sn',
'vacuna_obs',
'vacuna_dosis',
'vacuna_interes',
'vacuna_etapa',
'usr_dep',
'usr_dep_sup',
'usr_cargo',
'usr_regpago',
'usr_extension',
'usr_piso',
'usr_datebirth',
'ctrl_pedidoalmacen',
'ctrl_contacto',
'usr_emergencia',
'upd_date',
'active',
'groupid',
'habilita_almacen',
'estado_vinculacion_mincit',
'usr_firma',
'usr_firma_b',
'usr_hojaruta',
'reset_token',
'reset_date',
'usr_edl',
'phone',
'phone1',
'usr_directivo',
'vacuna_autoriza',
'vacuna_autoriza_email',
'two_factor',
'totp' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'idusrglobal' => array( 'export_field' ),
'id_fk' => array( 'export_field1' ),
'Username' => array( 'export_field2' ),
'Password' => array( 'export_field3' ),
'usr_email' => array( 'export_field4' ),
'usr_name' => array( 'export_field5' ),
'usr_lname' => array( 'export_field6' ),
'usr_nombresfull' => array( 'export_field7' ),
'usr_personalid' => array( 'export_field8' ),
'usr_inicial' => array( 'export_field9' ),
'usr_sessini' => array( 'export_field10' ),
'usr_image' => array( 'export_field11' ),
'usr_status_nomina' => array( 'export_field12' ),
'usr_status' => array( 'export_field13' ),
'usr_rdnkey' => array( 'export_field14' ),
'usr_type_vinc' => array( 'export_field15' ),
'usr_type_vinculacion' => array( 'export_field16' ),
'usr_status_sol' => array( 'export_field17' ),
'usr_dependencia' => array( 'export_field18' ),
'user_dep' => array( 'export_field19' ),
'usr_entidad' => array( 'export_field20' ),
'usr_not' => array( 'export_field21' ),
'usr_not_msj' => array( 'export_field22' ),
'usr_jefe' => array( 'export_field23' ),
'usr_minequipo_lider' => array( 'export_field24' ),
'usr_minequipo_grupo' => array( 'export_field25' ),
'global_rol_me' => array( 'export_field26' ),
'global_rol_gh' => array( 'export_field27' ),
'global_rol_almacen' => array( 'export_field28' ),
'global_rol_ci' => array( 'export_field29' ),
'global_rol_contratos' => array( 'export_field30' ),
'global_rol_hojar' => array( 'export_field31' ),
'global_rol_inmuebles' => array( 'export_field32' ),
'global_rol_siis' => array( 'export_field33' ),
'global_rol_cpanel' => array( 'export_field34' ),
'global_rol_dashboard' => array( 'export_field35' ),
'global_rol_zf' => array( 'export_field36' ),
'global_rol_sipi' => array( 'export_field37' ),
'global_rol_cej' => array( 'export_field38' ),
'global_rol_jc3' => array( 'export_field39' ),
'global_rol_th' => array( 'export_field40' ),
'global_rol_sid' => array( 'export_field41' ),
'global_rol' => array( 'export_field42' ),
'global_rol_cont' => array( 'export_field43' ),
'globla_rol_ct' => array( 'export_field44' ),
'global_rol_procjur' => array( 'export_field45' ),
'global_rol_comacc' => array( 'export_field46' ),
'global_rol_gestion' => array( 'export_field47' ),
'global_rol_ciudadano' => array( 'export_field48' ),
'global_rol_ciudadano_dep' => array( 'export_field49' ),
'sys_user' => array( 'export_field50' ),
'sys_date' => array( 'export_field51' ),
'sys_time' => array( 'export_field52' ),
'sys_ntries_usr' => array( 'export_field53' ),
'sys_registrationdate_usr' => array( 'export_field54' ),
'sys_expiration_usr' => array( 'export_field55' ),
'sys_disabledate_usr' => array( 'export_field56' ),
'sys_upd_fecha' => array( 'export_field57' ),
'sys_upd_user' => array( 'export_field58' ),
'sys_upd_time' => array( 'export_field59' ),
'sys_update_info' => array( 'export_field60' ),
'sys_update_family_info' => array( 'export_field61' ),
'usr_update_almacen' => array( 'export_field62' ),
'sys_anio' => array( 'export_field63' ),
'ctrl' => array( 'export_field64' ),
'ext_security_id' => array( 'export_field65' ),
'covid_sn' => array( 'export_field66' ),
'covid_fecha' => array( 'export_field67' ),
'vacuna_sn' => array( 'export_field68' ),
'vacuna_nombre' => array( 'export_field69' ),
'vacuna_a_fecha' => array( 'export_field70' ),
'vacuna_b_fechaprog' => array( 'export_field71' ),
'vacuna_b_fecha' => array( 'export_field72' ),
'vacuna_c_fecha' => array( 'export_field73' ),
'vacuna_consentimiento_sn' => array( 'export_field74' ),
'vacuna_obs' => array( 'export_field75' ),
'vacuna_dosis' => array( 'export_field76' ),
'vacuna_interes' => array( 'export_field77' ),
'vacuna_etapa' => array( 'export_field78' ),
'usr_dep' => array( 'export_field79' ),
'usr_dep_sup' => array( 'export_field80' ),
'usr_cargo' => array( 'export_field81' ),
'usr_regpago' => array( 'export_field82' ),
'usr_extension' => array( 'export_field83' ),
'usr_piso' => array( 'export_field84' ),
'usr_datebirth' => array( 'export_field85' ),
'ctrl_pedidoalmacen' => array( 'export_field86' ),
'ctrl_contacto' => array( 'export_field87' ),
'usr_emergencia' => array( 'export_field88' ),
'upd_date' => array( 'export_field89' ),
'active' => array( 'export_field90' ),
'groupid' => array( 'export_field91' ),
'habilita_almacen' => array( 'export_field92' ),
'estado_vinculacion_mincit' => array( 'export_field93' ),
'usr_firma' => array( 'export_field94' ),
'usr_firma_b' => array( 'export_field95' ),
'usr_hojaruta' => array( 'export_field96' ),
'reset_token' => array( 'export_field97' ),
'reset_date' => array( 'export_field98' ),
'usr_edl' => array( 'export_field99' ),
'phone' => array( 'export_field100' ),
'phone1' => array( 'export_field101' ),
'usr_directivo' => array( 'export_field102' ),
'vacuna_autoriza' => array( 'export_field103' ),
'vacuna_autoriza_email' => array( 'export_field104' ),
'two_factor' => array( 'export_field105' ),
'totp' => array( 'export_field106' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104',
'export_field105',
'export_field106' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field62' => 'grid',
'export_field63' => 'grid',
'export_field64' => 'grid',
'export_field65' => 'grid',
'export_field66' => 'grid',
'export_field67' => 'grid',
'export_field68' => 'grid',
'export_field69' => 'grid',
'export_field70' => 'grid',
'export_field71' => 'grid',
'export_field72' => 'grid',
'export_field73' => 'grid',
'export_field74' => 'grid',
'export_field75' => 'grid',
'export_field76' => 'grid',
'export_field77' => 'grid',
'export_field78' => 'grid',
'export_field79' => 'grid',
'export_field80' => 'grid',
'export_field81' => 'grid',
'export_field82' => 'grid',
'export_field83' => 'grid',
'export_field84' => 'grid',
'export_field85' => 'grid',
'export_field86' => 'grid',
'export_field87' => 'grid',
'export_field88' => 'grid',
'export_field89' => 'grid',
'export_field90' => 'grid',
'export_field91' => 'grid',
'export_field92' => 'grid',
'export_field93' => 'grid',
'export_field94' => 'grid',
'export_field95' => 'grid',
'export_field96' => 'grid',
'export_field97' => 'grid',
'export_field98' => 'grid',
'export_field99' => 'grid',
'export_field100' => 'grid',
'export_field101' => 'grid',
'export_field102' => 'grid',
'export_field103' => 'grid',
'export_field104' => 'grid',
'export_field105' => 'grid',
'export_field106' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104',
'export_field105',
'export_field106' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104',
'export_field105',
'export_field106' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'idusrglobal',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'id_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Username',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Password',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'usr_email',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'usr_name',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'usr_lname',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'usr_nombresfull',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'usr_personalid',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'usr_inicial',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'usr_sessini',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'usr_image',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'usr_status_nomina',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'usr_status',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'usr_rdnkey',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'usr_type_vinc',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'usr_type_vinculacion',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'usr_status_sol',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'usr_dependencia',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'user_dep',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'usr_entidad',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'usr_not',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'usr_not_msj',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'usr_jefe',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'usr_minequipo_lider',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'usr_minequipo_grupo',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'global_rol_me',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'global_rol_gh',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'global_rol_almacen',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'global_rol_ci',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'global_rol_contratos',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'global_rol_hojar',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'global_rol_inmuebles',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'global_rol_siis',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'global_rol_cpanel',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'global_rol_dashboard',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'global_rol_zf',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'global_rol_sipi',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'global_rol_cej',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'global_rol_jc3',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'global_rol_th',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'global_rol_sid',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'global_rol',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'global_rol_cont',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'globla_rol_ct',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'global_rol_procjur',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'global_rol_comacc',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'global_rol_gestion',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'global_rol_ciudadano',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'global_rol_ciudadano_dep',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'sys_date',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'sys_time',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'sys_ntries_usr',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'sys_registrationdate_usr',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'sys_expiration_usr',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'sys_disabledate_usr',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'sys_upd_fecha',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'sys_upd_user',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'sys_upd_time',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'sys_update_info',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'sys_update_family_info',
'type' => 'export_field' ),
'export_field62' => array( 'field' => 'usr_update_almacen',
'type' => 'export_field' ),
'export_field63' => array( 'field' => 'sys_anio',
'type' => 'export_field' ),
'export_field64' => array( 'field' => 'ctrl',
'type' => 'export_field' ),
'export_field65' => array( 'field' => 'ext_security_id',
'type' => 'export_field' ),
'export_field66' => array( 'field' => 'covid_sn',
'type' => 'export_field' ),
'export_field67' => array( 'field' => 'covid_fecha',
'type' => 'export_field' ),
'export_field68' => array( 'field' => 'vacuna_sn',
'type' => 'export_field' ),
'export_field69' => array( 'field' => 'vacuna_nombre',
'type' => 'export_field' ),
'export_field70' => array( 'field' => 'vacuna_a_fecha',
'type' => 'export_field' ),
'export_field71' => array( 'field' => 'vacuna_b_fechaprog',
'type' => 'export_field' ),
'export_field72' => array( 'field' => 'vacuna_b_fecha',
'type' => 'export_field' ),
'export_field73' => array( 'field' => 'vacuna_c_fecha',
'type' => 'export_field' ),
'export_field74' => array( 'field' => 'vacuna_consentimiento_sn',
'type' => 'export_field' ),
'export_field75' => array( 'field' => 'vacuna_obs',
'type' => 'export_field' ),
'export_field76' => array( 'field' => 'vacuna_dosis',
'type' => 'export_field' ),
'export_field77' => array( 'field' => 'vacuna_interes',
'type' => 'export_field' ),
'export_field78' => array( 'field' => 'vacuna_etapa',
'type' => 'export_field' ),
'export_field79' => array( 'field' => 'usr_dep',
'type' => 'export_field' ),
'export_field80' => array( 'field' => 'usr_dep_sup',
'type' => 'export_field' ),
'export_field81' => array( 'field' => 'usr_cargo',
'type' => 'export_field' ),
'export_field82' => array( 'field' => 'usr_regpago',
'type' => 'export_field' ),
'export_field83' => array( 'field' => 'usr_extension',
'type' => 'export_field' ),
'export_field84' => array( 'field' => 'usr_piso',
'type' => 'export_field' ),
'export_field85' => array( 'field' => 'usr_datebirth',
'type' => 'export_field' ),
'export_field86' => array( 'field' => 'ctrl_pedidoalmacen',
'type' => 'export_field' ),
'export_field87' => array( 'field' => 'ctrl_contacto',
'type' => 'export_field' ),
'export_field88' => array( 'field' => 'usr_emergencia',
'type' => 'export_field' ),
'export_field89' => array( 'field' => 'upd_date',
'type' => 'export_field' ),
'export_field90' => array( 'field' => 'active',
'type' => 'export_field' ),
'export_field91' => array( 'field' => 'groupid',
'type' => 'export_field' ),
'export_field92' => array( 'field' => 'habilita_almacen',
'type' => 'export_field' ),
'export_field93' => array( 'field' => 'estado_vinculacion_mincit',
'type' => 'export_field' ),
'export_field94' => array( 'field' => 'usr_firma',
'type' => 'export_field' ),
'export_field95' => array( 'field' => 'usr_firma_b',
'type' => 'export_field' ),
'export_field96' => array( 'field' => 'usr_hojaruta',
'type' => 'export_field' ),
'export_field97' => array( 'field' => 'reset_token',
'type' => 'export_field' ),
'export_field98' => array( 'field' => 'reset_date',
'type' => 'export_field' ),
'export_field99' => array( 'field' => 'usr_edl',
'type' => 'export_field' ),
'export_field100' => array( 'field' => 'phone',
'type' => 'export_field' ),
'export_field101' => array( 'field' => 'phone1',
'type' => 'export_field' ),
'export_field102' => array( 'field' => 'usr_directivo',
'type' => 'export_field' ),
'export_field103' => array( 'field' => 'vacuna_autoriza',
'type' => 'export_field' ),
'export_field104' => array( 'field' => 'vacuna_autoriza_email',
'type' => 'export_field' ),
'export_field105' => array( 'field' => 'two_factor',
'type' => 'export_field' ),
'export_field106' => array( 'field' => 'totp',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>